Numpy Arrays

In [3]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [5]:
my_list = [1,2,3]

In [6]:
my_list

[1, 2, 3]

In [7]:
import  numpy as np

In [8]:
arr   = np.array(my_list)

In [9]:
arr

array([1, 2, 3])

In [10]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [11]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
range(0,10)

range(0, 10)

In [14]:
np.arange(0,100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [15]:
np.arange(0,100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [16]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [17]:
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [18]:
np.zeros(3)

array([0., 0., 0.])

In [19]:
np.zeros((3,3)) #( - row, (- clumm

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
np.ones((5,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [24]:
np.linspace(100,500,10)

array([100.        , 144.44444444, 188.88888889, 233.33333333,
       277.77777778, 322.22222222, 366.66666667, 411.11111111,
       455.55555556, 500.        ])

In [25]:
np.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [26]:
np.random.rand(5)

array([0.15697511, 0.98975527, 0.07718729, 0.99486652, 0.66771818])

In [27]:
np.random.rand(5,7)

array([[0.41876223, 0.21596051, 0.48196925, 0.839201  , 0.40097168,
        0.62823022, 0.99449725],
       [0.39902399, 0.35017234, 0.98568892, 0.13678064, 0.02621006,
        0.9588001 , 0.66925586],
       [0.01886511, 0.62086149, 0.72942768, 0.60112274, 0.37653955,
        0.10713955, 0.34394225],
       [0.35003204, 0.83641908, 0.73176226, 0.99150223, 0.72481732,
        0.40377461, 0.64270848],
       [0.06389073, 0.49819827, 0.26147083, 0.3129496 , 0.77387915,
        0.59329533, 0.89772488]])

In [29]:
np.random.randint(1,100)

69

In [30]:
np.random.randint(1,100,30)

array([78, 50, 64, 32,  2, 25, 56, 39, 45, 51, 65,  9,  9,  9, 16, 18, 24,
       12, 24, 19, 66, 40, 46, 35, 93, 36, 61, 79,  5, 84], dtype=int32)

In [33]:
arr = np.arange(1,100,2)

In [34]:
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [35]:
ranarr = np.random.randint(0,50,10)

In [36]:
ranarr.shape

(10,)

In [37]:
ranarr.reshape(5,2)

array([[ 8, 22],
       [35, 22],
       [ 1, 37],
       [11,  4],
       [14, 33]], dtype=int32)

In [38]:
arr.shape

(50,)

In [41]:
ranarr.max()

np.int32(37)

In [40]:
arr.reshape(5,10)

array([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29, 31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49, 51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69, 71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89, 91, 93, 95, 97, 99]])

In [42]:
print(ranarr.max())

37


In [43]:
ranarr.min()

np.int32(1)

In [44]:
ranarr.argmax() #max er index

np.int64(5)

In [45]:
ranarr

array([ 8, 22, 35, 22,  1, 37, 11,  4, 14, 33], dtype=int32)

In [46]:
ranarr.argmax() #max er index

np.int64(5)

In [47]:
type(arr)

numpy.ndarray

In [49]:
arr.dtype

dtype('int64')

Numpy Arry Indexing

In [65]:
arr2 = np.arange(0,10)

In [66]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
arr2[8]

np.int64(8)

In [68]:
arr2[1:5]

array([1, 2, 3, 4])

In [69]:
arr2[:6]

array([0, 1, 2, 3, 4, 5])

In [70]:
arr2[0:5]  = 100

In [71]:
arr2

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [72]:
arr2 = np.arange(0,10)

In [75]:
s_arr= arr2[0:5]

In [76]:
s_arr

array([0, 1, 2, 3, 4])

In [77]:
s_arr[::] =100

In [78]:
s_arr

array([100, 100, 100, 100, 100])

In [79]:
arr2

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

Arry copy

In [83]:
arr_copy = arr2.copy()

In [84]:
arr_copy[0:5] = 500

In [85]:
arr2

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [86]:
arr_copy

array([500, 500, 500, 500, 500,   5,   6,   7,   8,   9])

In [87]:
## 2D Array

In [90]:
arr_2d = np.array([[10,25,75],[37,49,21],[8,34,21]])

In [91]:
arr_2d

array([[10, 25, 75],
       [37, 49, 21],
       [ 8, 34, 21]])

In [92]:
arr_2d[0] # first row

array([10, 25, 75])

In [93]:
arr_2d[0][1] # second row

np.int64(25)

In [94]:
arr_2d[1][2]

np.int64(21)

In [95]:
arr_2d

array([[10, 25, 75],
       [37, 49, 21],
       [ 8, 34, 21]])

In [96]:
arr_2d[:2] # row

array([[10, 25, 75],
       [37, 49, 21]])

In [99]:
arr_2d[0:2,1:3]

array([[25, 75],
       [49, 21]])

In [100]:
arr_2d[:2,1:]

array([[25, 75],
       [49, 21]])

In [102]:
arr_2d[1:, :2]

array([[37, 49],
       [ 8, 34]])

In [103]:
arr2 = np.arange(0,10)

In [104]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
arr2 >5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [106]:
arr2[arr2 >5]

array([6, 7, 8, 9])

In [107]:
arr2 = np.arange(50).reshape(5,10)

In [108]:
arr_2d

array([[10, 25, 75],
       [37, 49, 21],
       [ 8, 34, 21]])

In [109]:
arr_2d[2:4, 5:7]

array([], shape=(1, 0), dtype=int64)

## Numpy  Operation

In [111]:
arr = np.arange(0,11)

In [112]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [113]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [114]:
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [115]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [116]:
arr/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [117]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [118]:
arr/arr

C:\Users\sklif\AppData\Local\Temp\ipykernel_9424\1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [119]:
1/0

ZeroDivisionError: division by zero

In [120]:
1/1

1.0

In [121]:
1/arr

C:\Users\sklif\AppData\Local\Temp\ipykernel_9424\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [122]:
arr/1

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [123]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [124]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [125]:
np.max(arr)

np.int64(10)

In [126]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [127]:
np.log(arr)

C:\Users\sklif\AppData\Local\Temp\ipykernel_9424\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])